### PR TITLE
added no-zone autorender

### PR DESCRIPTION
**Pull request by ilyavf**
Adding a no-zone option for autorender.

Usage:
```html
<script src="node_modules/steal/steal.js"
        main="index.stache!done-autorender/src/no-zone"></script>
```

### CODE REVIEW

**Comment by ilyavf** [comment]
@matthewp 

>reattach is still being called here which does use Zones

Fixed.

> I would change it so that can-zone is not imported when in noZone mode

Fixed.

**Comment by matthewp** [comment]
👍 Think it's good now.

**Comment by frank-dspeed** [comment]
will add that to my prove repo now and verify!

**Comment by frank-dspeed** [comment]
@chasenlehara can we add the info that this no-zone option is needed when using socket.io because of its incompatibility with can-zone and so on with SSR? if you want to build and serve production bundels for example via http.

**Comment by matthewp** [comment]
Closes #27

**Pull request merged**
