### PR TITLE
Support optimized builds

### PR DESCRIPTION
**Pull request by m-mujica**
- Remove old references to System
- Make `@loader` and `@steal` explicit dependencies

Closes https://github.com/stealjs/steal-tools/issues/845

### CODE REVIEW

**Comment by m-mujica** [comment]
Since the new test requires the latest steal-tools to be available, we could either:

a) get a release of steal-tools#master in its current state to update this PR.
b) Keep this PR open until I get the bitcentive build working and release steal-tools at that point

Also, I'm not very happy with the test I added:

Funcunit relies on the global `steal.done` to signal that `F.open` was successful. We could:

1) Update Funcunit  so it explicitly requires `@steal` (although funcunit relies on a very old steal)
2) Rename the global on the slim loader as suggested in other issue
3) Remove that random timeout (somehow) I added to the test to make it more reliable. 

cc: @matthewp

**Comment by matthewp** [comment]
:+1

**Comment by matthewp** [comment]
Do a steal-tools release and then update this PR. There's definitely no breaking changes, so no reason not to release that (and then this, which also has no breaking changes).

I think your test is fine! The solution would be to upgrade FuncUnit, but not worth doing that at this time. I mean, aside from libraries like this, the chance that people are going to run FuncUnit tests against optimized builds seems fairly slim to me!

**Comment by m-mujica** [comment]
> against optimized builds seems fairly slim to me!

pp 550x550

**Comment by m-mujica** [comment]
@matthewp want me to do a patch release for this one? It's not really a new feature so I'd go for a patch release.

**Comment by matthewp** [comment]
Yep, bug fix sounds right

**Comment by m-mujica** [comment]
@matthewp I didn't notice but autorender@1.3.1 was already released here https://www.npmjs.com/package/done-autorender but the repo was not. 

I wonder if you forgot to push master and the tag. If you have it locally I can delete the tag and revert that last commit so we can merge in the stuff you have locally.

**Pull request merged**
